// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraSuaMoc.API.Data;

#nullable disable

namespace TraSuaMoc.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606075158_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraSuaMoc.API.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$tuAuoqRF5fx.h.RseKOtfOPl6dNHnL6ED2Sbtuet9O0ORdUT5MltO",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TraSuaMoc.API.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "trasua",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7577),
                            Description = "Trà oolong thơm, sữa tươi béo ngậy",
                            Emoji = "🧋",
                            IsHidden = false,
                            IsHot = true,
                            IsNew = false,
                            Name = "Trà Sữa Oolong",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "trasua",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7585),
                            Description = "Matcha Nhật nguyên chất hoà cùng sữa tươi",
                            Emoji = "🍵",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = true,
                            Name = "Trà Sữa Matcha",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "trasua",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7586),
                            Description = "Dâu tây tươi xay nhuyễn, sữa tươi, trân châu đỏ",
                            Emoji = "🍓",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Trà Sữa Dâu",
                            Price = 37000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "trasua",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7589),
                            Description = "Khoai môn tím thuần chất, vị bùi ngọt đặc trưng",
                            Emoji = "💜",
                            IsHidden = false,
                            IsHot = true,
                            IsNew = false,
                            Name = "Trà Sữa Taro",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "cafe",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7590),
                            Description = "Cà phê phin truyền thống, sữa đặc ngọt thơm",
                            Emoji = "☕",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Cà Phê Sữa Đá",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "cafe",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7591),
                            Description = "Cà phê nhẹ, nhiều sữa, thích hợp buổi chiều",
                            Emoji = "🥛",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Bạc Xỉu",
                            Price = 28000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "cafe",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7591),
                            Description = "Ủ lạnh 12 giờ, hương thơm đậm đà, không đắng",
                            Emoji = "🧊",
                            IsHidden = false,
                            IsHot = true,
                            IsNew = false,
                            Name = "Cold Brew",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "sinh-to",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7592),
                            Description = "Bơ chín 100%, thêm sữa đặc và đá xay mịn",
                            Emoji = "🥑",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Sinh Tố Bơ",
                            Price = 40000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "sinh-to",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7593),
                            Description = "Xoài cát Hoà Lộc ngọt lịm, đá xay mát lạnh",
                            Emoji = "🥭",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = true,
                            Name = "Sinh Tố Xoài",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "nuoc-ep",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7594),
                            Description = "Cam vắt tươi mỗi ngày, vitamin C dồi dào",
                            Emoji = "🍊",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Nước Ép Cam",
                            Price = 32000m
                        },
                        new
                        {
                            Id = 11,
                            Category = "nuoc-ep",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7595),
                            Description = "Dưa hấu mùa hè tươi ngọt, mát lạnh sảng khoái",
                            Emoji = "🍉",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Nước Ép Dưa Hấu",
                            Price = 30000m
                        },
                        new
                        {
                            Id = 12,
                            Category = "tra",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7596),
                            Description = "Kết hợp đào, cam và sả, vị chua ngọt dịu mát",
                            Emoji = "🍑",
                            IsHidden = false,
                            IsHot = true,
                            IsNew = false,
                            Name = "Trà Đào Cam Sả",
                            Price = 33000m
                        },
                        new
                        {
                            Id = 13,
                            Category = "tra",
                            CreatedAt = new DateTime(2026, 6, 6, 7, 51, 58, 193, DateTimeKind.Utc).AddTicks(7597),
                            Description = "Chanh dây nhiệt đới chua nhẹ, thơm mát",
                            Emoji = "🟡",
                            IsHidden = false,
                            IsHot = false,
                            IsNew = false,
                            Name = "Trà Chanh Leo",
                            Price = 30000m
                        });
                });

            modelBuilder.Entity("TraSuaMoc.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TraSuaMoc.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TraSuaMoc.API.Models.OrderItem", b =>
                {
                    b.HasOne("TraSuaMoc.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TraSuaMoc.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
